[tool.black]
line-length = 88
target-version = ["py311"] 

[tool.isort]
profile = "black"
multi_line_output = 3
known_first_party = ["src"]
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
skip = ["migrations", "alembic", ".git", "__pycache__"]
skip_glob = ["**/migrations/**"]

[tool.flake8]
max-line-length = 88
ignore = ["E203", "W503"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
filterwarnings = [
    "ignore::DeprecationWarning:passlib.*",
    "ignore::DeprecationWarning:sqlalchemy.*",
    "ignore::UserWarning",
]
log_cli = true
log_cli_level = "INFO"
log_format = "%(asctime)s [%(levelname)s] %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"
markers = [
    "unit: marque les tests unitaires",
    "integration: marque les tests d'intégration",
    "e2e: marque les tests end-to-end",
    "slow: marque les tests longs (désactivés par défaut)",
]
